### PR TITLE
Google Translate API integrated

### PR DESCRIPTION
**Pull request by chankruze**
It is simplified now.You should review the code & i think this is mergable.

### CODE REVIEW

**Comment by chankruze** [comment]
Hi @mwarning i am just informing you that
I used js to add **Google Translate API** in both pull request #17 & #18 but i closed #17 because i found it will be more informative if i include the function in shared.js.

There is no conflict with this code therefore i am asking to review and merge it.It will be very helpful for non german users to understant web interface.

**Comment by mwarning** [comment]
hi @geekofia, thanks for your effort. I need to think about a solution here. The problem is, that the router is expected to work without Internet access. This makes it desirable to have translations working without Internet access.

**Comment by chankruze** [comment]
First of all thanks for reviewing.You have a solid point.I will think a solution for it.

**Comment by chankruze** [comment]
I think now only solution is to save translations to a variable in separate js file. We can call a function with event listener to change language on click.

**Comment by mwarning** [comment]
I agree.

**Comment by chankruze** [comment]
Is some one working on multi language support ? Or i should start working ?

**Comment by mwarning** [comment]
hi @geekofia, I forgot about this ticket. Sorry about that.
How about something like this: https://github.com/freifunk-bielefeld/firmware/commit/d013faa6a6df31c12e54c9f4248a7c352e5b1998

It's really simple but might work. Translations are not integrated yet.
The language of the default text could be english.

**Comment by chankruze** [comment]
Yes that should work.Need the whole lines to be translated.I have translated them.If need you can comment.

**Comment by mwarning** [comment]
I think it is better to translate the whole lines.
Can you do a pull request with the translations?
Then I can merge them. :-)

**Comment by chankruze** [comment]
please see closed pull request #16.And let me know is that what you need or anything else ?

**Comment by mwarning** [comment]
The data is all there. But it need to be put together :-)
The branch from #16 is not available anymore. So this will be a lot of manual work.

**Comment by chankruze** [comment]
I am translating (like #16), clean forked and if i translate the german lines to english in html and js (help texts) ..then the german will be replaced with english ... is it okay ?

**Comment by mwarning** [comment]
That would be great! Anyway, time for me to go to bed now.

**Pull request closed without merging**
