### PR TITLE
Translated to English

### PR DESCRIPTION
**Pull request by chankruze**
@mwarning I have translated whole lines to English.Review and merge if you are happy.

### CODE REVIEW

**Comment by mwarning** [comment]
thanks

**Comment by chankruze** [comment]
Is there something more you need ?
Check if it has conflicts if not then merge it.

**Comment by mwarning** [comment]
We need to move the english and german texts into translations.js. Then every place need to be annotated with class="tr-...", but this would not work every time.

There is still a bunch of work ahead.

**Comment by mwarning** [comment]
The current progress is here: https://github.com/freifunk-bielefeld/firmware/compare/i18n
When it is finished, it will be merged into ffulm:master.

Stuff is still messy and might get some simplification. The main task will be to finish translations.js and put the tr-* strings in all the .html and .js files.

**Comment by chankruze** [comment]
What is the progress for translation.js ?
Btw it is a lot of hard manual work.

**Comment by mwarning** [comment]
I have been working on the feature over the last few days. There are a few bugs left that I need to fix.

**Comment by chankruze** [comment]
One small request,please uncomment the MAC-address changer lines.If we can do that from web interface,then it will be easy to setup PPOE sience most of ISP bind MAC address of user's router to their data table,therefore they need to clone registered MAC( already happened with me😂).

I mean this snippet :https://github.com/geekofia/firmware/commit/1ce866876c39c592865ac15384435b2629c6122f

**Pull request merged**
